export type IconNames =
  | "icon-arrow-narrow-left"
  | "icon-check"
  | "icon-heart"
  | "icon-link-external-02"
  | "icon-list"
  | "icon-loading-01"
  | "icon-log-in-01"
  | "icon-log-out-01"
  | "icon-trash-01"
  | "icon-user-01"
  | "icon-upload-cloud-02"
  | "icon-x-close"
