export type IconNames =
  | "icon-check"
  | "icon-heart"
  | "icon-link-external-02"
  | "icon-list"
  | "icon-log-in-01"
  | "icon-log-out-01"
  | "icon-user-01"
  | "icon-upload-cloud-02"
  | "icon-x-close"
